language: c

compiler:
  - gcc

before_script:
  - ./bootstrap
  - ./configure
  - make

script:
  - make check

notifications:
  email:
    recipients:
      - bzm@2bz.de
    on_success: change
    on_failure: always
